baseURL = 'https://localpestco.pages.dev/'
languageCode = 'en-us'
title = 'Local Pest Co'
# theme removed to use custom layouts
min_version = '0.146.0'
disableKinds = ['taxonomy', 'term']
enableGitInfo = true

[outputs]
home = ['HTML', 'RSS', 'Robots']
section = ['HTML', 'RSS']

[outputFormats]
  [outputFormats.Robots]
    mediaType = 'text/plain'
    baseName = 'robots'
    isPlainText = true

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[params]
  # canonical production URL used for canonicals and sitemap
  productionBaseURL = 'https://localpest.co/'
  # optional title suffix appended to page titles
  titleSuffix = ''
  # Google Analytics ID (GA4)
  ga_id = 'G-E3J58VK95M'
  # social accounts
  [params.social]
    twitter = ''
