baseURL = 'https://localpest.co/'
languageCode = 'en-us'
title = 'Local Pest Co'
# theme removed to use custom layouts
min_version = '0.146.0'
disableKinds = ['taxonomy', 'term']
enableGitInfo = true

[outputs]
home = ['HTML', 'RSS', 'Robots']
section = ['HTML', 'RSS']

[outputFormats]
  [outputFormats.Robots]
    mediaType = 'text/plain'
    baseName = 'robots'
    isPlainText = true

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[params]
  # canonical production URL used for canonicals and sitemap
  productionBaseURL = 'https://localpest.co/'
  # optional title suffix appended to page titles
  titleSuffix = ''
  # Google Analytics ID (GA4)
  ga_id = 'G-E3J58VK95M'
  # logo used in header, favicon, and structured data
  logo = '/images/logo-placeholder.svg'
  # social accounts
  [params.social]
    facebook = 'https://www.facebook.com/Localpestco/'
    twitter = ''
  [params.business]
    name = 'Local Pest Co'
    legalName = 'Local Pest Co'
    phone = '+61-405-508-035'
    email = 'thelocalpestco@bigpond.com'
    priceRange = '$$'
    areaServed = ['Kingscliff NSW', 'Tweed Coast NSW', 'Northern Rivers NSW']
    openingHours = ['Mo-Su 08:00-18:00']
    sameAs = ['https://www.facebook.com/Localpestco/', 'https://www.facebook.com/xstreamfly/', 'https://www.instagram.com/xstream_fly/']
    [params.business.address]
      streetAddress = '23 Dinsey Street'
      addressLocality = 'Kingscliff'
      addressRegion = 'NSW'
      postalCode = '2487'
      addressCountry = 'AU'
    [params.business.geo]
      latitude = -28.2638497
      longitude = 153.57372
